from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CorpusUrl:
    identifier: str
    category: str
    publisher: str
    document_shape: str
    url: str


CORPUS: tuple[CorpusUrl, ...] = (
    CorpusUrl(
        "official-en-01",
        "Official English announcements",
        "OpenAI",
        "news index",
        "https://openai.com/news/",
    ),
    CorpusUrl(
        "official-en-02",
        "Official English announcements",
        "Anthropic",
        "news index",
        "https://www.anthropic.com/news",
    ),
    CorpusUrl(
        "official-en-03",
        "Official English announcements",
        "Google AI",
        "topic blog index",
        "https://blog.google/technology/ai/",
    ),
    CorpusUrl(
        "official-en-04",
        "Official English announcements",
        "Google DeepMind",
        "research blog index",
        "https://deepmind.google/discover/blog/",
    ),
    CorpusUrl(
        "official-en-05",
        "Official English announcements",
        "Meta AI",
        "blog index",
        "https://ai.meta.com/blog/",
    ),
    CorpusUrl(
        "official-en-06",
        "Official English announcements",
        "Microsoft Research",
        "blog index",
        "https://www.microsoft.com/en-us/research/blog/",
    ),
    CorpusUrl(
        "official-en-07",
        "Official English announcements",
        "NVIDIA",
        "category blog index",
        "https://blogs.nvidia.com/blog/category/generative-ai/",
    ),
    CorpusUrl(
        "official-en-08",
        "Official English announcements",
        "Hugging Face",
        "community blog index",
        "https://huggingface.co/blog",
    ),
    CorpusUrl(
        "official-en-09",
        "Official English announcements",
        "DeepSeek",
        "product landing page",
        "https://www.deepseek.com/",
    ),
    CorpusUrl(
        "official-en-10",
        "Official English announcements",
        "Qwen",
        "official blog index",
        "https://qwen.ai/blog/",
    ),
    CorpusUrl(
        "chinese-media-01",
        "Chinese technical media",
        "Machine Heart",
        "article index",
        "https://www.jiqizhixin.com/articles",
    ),
    CorpusUrl(
        "chinese-media-02",
        "Chinese technical media",
        "Qbitai",
        "site home",
        "https://www.qbitai.com/",
    ),
    CorpusUrl(
        "chinese-media-03",
        "Chinese technical media",
        "Qbitai",
        "WordPress feed",
        "https://www.qbitai.com/feed/",
    ),
    CorpusUrl(
        "chinese-media-04",
        "Chinese technical media",
        "Leiphone",
        "AI category",
        "https://www.leiphone.com/category/ai",
    ),
    CorpusUrl(
        "chinese-media-05",
        "Chinese technical media",
        "InfoQ China",
        "AI topic",
        "https://www.infoq.cn/topic/AI",
    ),
    CorpusUrl(
        "chinese-media-06",
        "Chinese technical media",
        "36Kr",
        "technology index",
        "https://www.36kr.com/information/technology/",
    ),
    CorpusUrl(
        "chinese-media-07",
        "Chinese technical media",
        "IT Home",
        "AI tag",
        "https://www.ithome.com/0/taglist/ai/",
    ),
    CorpusUrl(
        "chinese-media-08",
        "Chinese technical media",
        "Aixinzhijie",
        "AI news index",
        "https://www.aixinzhijie.com/",
    ),
    CorpusUrl(
        "chinese-media-09",
        "Chinese technical media",
        "Synced Review",
        "Chinese home",
        "https://syncedreview.com/",
    ),
    CorpusUrl(
        "chinese-media-10",
        "Chinese technical media",
        "AI Era",
        "article index",
        "https://www.51cto.com/aigc/",
    ),
    CorpusUrl(
        "dynamic-01",
        "Dynamic product pages",
        "Qwen Chat",
        "client-rendered application",
        "https://chat.qwen.ai/",
    ),
    CorpusUrl(
        "dynamic-02",
        "Dynamic product pages",
        "Hugging Face Spaces",
        "interactive app directory",
        "https://huggingface.co/spaces",
    ),
    CorpusUrl(
        "dynamic-03",
        "Dynamic product pages",
        "OpenAI Platform",
        "documentation app",
        "https://platform.openai.com/docs",
    ),
    CorpusUrl(
        "dynamic-04",
        "Dynamic product pages",
        "Anthropic Console Docs",
        "documentation app",
        "https://docs.anthropic.com/",
    ),
    CorpusUrl(
        "dynamic-05",
        "Dynamic product pages",
        "DeepSeek API Docs",
        "documentation app",
        "https://api-docs.deepseek.com/",
    ),
    CorpusUrl(
        "dynamic-06",
        "Dynamic product pages",
        "Kimi",
        "product landing page",
        "https://kimi.moonshot.cn/",
    ),
    CorpusUrl(
        "dynamic-07",
        "Dynamic product pages",
        "Perplexity",
        "product landing page",
        "https://www.perplexity.ai/",
    ),
    CorpusUrl(
        "dynamic-08", "Dynamic product pages", "Poe", "product landing page", "https://poe.com/"
    ),
    CorpusUrl(
        "dynamic-09",
        "Dynamic product pages",
        "Character.AI",
        "product landing page",
        "https://character.ai/",
    ),
    CorpusUrl(
        "dynamic-10",
        "Dynamic product pages",
        "Cursor",
        "product changelog app",
        "https://www.cursor.com/changelog",
    ),
    CorpusUrl(
        "technical-01",
        "Technical docs and changelogs",
        "GitHub Blog",
        "changelog feed",
        "https://github.blog/changelog/feed/",
    ),
    CorpusUrl(
        "technical-02",
        "Technical docs and changelogs",
        "GitHub Blog",
        "AI and ML feed",
        "https://github.blog/ai-and-ml/feed/",
    ),
    CorpusUrl(
        "technical-03",
        "Technical docs and changelogs",
        "OpenAI Platform",
        "API changelog",
        "https://platform.openai.com/docs/changelog",
    ),
    CorpusUrl(
        "technical-04",
        "Technical docs and changelogs",
        "Anthropic Docs",
        "release notes",
        "https://docs.anthropic.com/en/release-notes/overview",
    ),
    CorpusUrl(
        "technical-05",
        "Technical docs and changelogs",
        "DeepSeek Docs",
        "news page",
        "https://api-docs.deepseek.com/news",
    ),
    CorpusUrl(
        "technical-06",
        "Technical docs and changelogs",
        "Hugging Face Docs",
        "transformers docs",
        "https://huggingface.co/docs/transformers/index",
    ),
    CorpusUrl(
        "technical-07",
        "Technical docs and changelogs",
        "LangChain",
        "documentation",
        "https://docs.langchain.com/",
    ),
    CorpusUrl(
        "technical-08",
        "Technical docs and changelogs",
        "LlamaIndex",
        "documentation",
        "https://docs.llamaindex.ai/",
    ),
    CorpusUrl(
        "technical-09",
        "Technical docs and changelogs",
        "PyTorch",
        "release notes",
        "https://github.com/pytorch/pytorch/releases",
    ),
    CorpusUrl(
        "technical-10",
        "Technical docs and changelogs",
        "vLLM",
        "documentation",
        "https://docs.vllm.ai/",
    ),
    CorpusUrl(
        "research-pdf-01",
        "Research papers and PDFs",
        "arXiv",
        "abstract page",
        "https://arxiv.org/abs/1706.03762",
    ),
    CorpusUrl(
        "research-pdf-02",
        "Research papers and PDFs",
        "arXiv",
        "PDF",
        "https://arxiv.org/pdf/1706.03762",
    ),
    CorpusUrl(
        "research-pdf-03",
        "Research papers and PDFs",
        "OpenReview",
        "paper forum",
        "https://openreview.net/forum?id=VtmBAGCN7o",
    ),
    CorpusUrl(
        "research-pdf-04",
        "Research papers and PDFs",
        "NeurIPS Proceedings",
        "paper abstract",
        "https://papers.nips.cc/paper_files/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html",
    ),
    CorpusUrl(
        "research-pdf-05",
        "Research papers and PDFs",
        "PMLR",
        "paper page",
        "https://proceedings.mlr.press/v202/",
    ),
    CorpusUrl(
        "research-pdf-06",
        "Research papers and PDFs",
        "Nature",
        "article landing page",
        "https://www.nature.com/articles/s41586-023-06004-9",
    ),
    CorpusUrl(
        "research-pdf-07",
        "Research papers and PDFs",
        "Science",
        "article landing page",
        "https://www.science.org/doi/10.1126/science.adj0998",
    ),
    CorpusUrl(
        "research-pdf-08",
        "Research papers and PDFs",
        "ACL Anthology",
        "paper page",
        "https://aclanthology.org/",
    ),
    CorpusUrl(
        "research-pdf-09",
        "Research papers and PDFs",
        "Papers with Code",
        "paper index",
        "https://paperswithcode.com/",
    ),
    CorpusUrl(
        "research-pdf-10",
        "Research papers and PDFs",
        "arXiv",
        "AI search query",
        "https://arxiv.org/search/cs?query=large+language+models&searchtype=all",
    ),
    CorpusUrl(
        "repo-release-01",
        "Repositories and releases",
        "GitHub API",
        "release API",
        "https://api.github.com/repos/huggingface/transformers/releases",
    ),
    CorpusUrl(
        "repo-release-02",
        "Repositories and releases",
        "GitHub API",
        "release API",
        "https://api.github.com/repos/vllm-project/vllm/releases",
    ),
    CorpusUrl(
        "repo-release-03",
        "Repositories and releases",
        "GitHub API",
        "release API",
        "https://api.github.com/repos/langchain-ai/langchain/releases",
    ),
    CorpusUrl(
        "repo-release-04",
        "Repositories and releases",
        "GitHub API",
        "release API",
        "https://api.github.com/repos/run-llama/llama_index/releases",
    ),
    CorpusUrl(
        "repo-release-05",
        "Repositories and releases",
        "GitHub",
        "repository page",
        "https://github.com/openai/openai-python",
    ),
    CorpusUrl(
        "repo-release-06",
        "Repositories and releases",
        "GitHub",
        "repository page",
        "https://github.com/anthropics/anthropic-sdk-python",
    ),
    CorpusUrl(
        "repo-release-07",
        "Repositories and releases",
        "GitHub",
        "repository page",
        "https://github.com/deepseek-ai/DeepSeek-V3",
    ),
    CorpusUrl(
        "repo-release-08",
        "Repositories and releases",
        "GitHub",
        "repository page",
        "https://github.com/QwenLM/Qwen3",
    ),
    CorpusUrl(
        "repo-release-09",
        "Repositories and releases",
        "GitHub",
        "repository releases",
        "https://github.com/pytorch/torchtune/releases",
    ),
    CorpusUrl(
        "repo-release-10",
        "Repositories and releases",
        "GitHub",
        "repository releases",
        "https://github.com/ggml-org/llama.cpp/releases",
    ),
)
